---
  - name: install ntp package
    apt: name=ntp state=present

  - name: remove default ntp configuration
    file:
      path=/etc/ntp.conf
      state=absent
  - name: copy new configuration file
    template:
      src=ntp.conf
      dest=/etc/ntp.conf
    notify:
      - restart ntp
