---
  - name: execute ntpdate command
    command: ntpdate -s ntp.ubuntu.com

  - name: install ntp package
    apt: name=ntp state=present

#  - name: update config according to region
#    template:
#      src=
#      dest=
#    notify:
#      - reload ntp
